--Exception Handling 
BEGIN TRY
SELECT 1/0;
END TRY
BEGIN CATCH
SELECT
@@ERROR AS ERROR,
ERROR_NUMBER() AS ErrorNumber,
ERROR_SEVERITY() AS ErrorServerity,
ERROR_STATE() AS ErrorState,
ERROR_PROCEDURE() AS ErrorProcedure,
ERROR_LINE() AS ErrorLine,
ERROR_MESSAGE() AS ErrorMessage;
END CATCH